name = "match-schedule"
pages_build_output_dir = "public"
compatibility_date = "2026-06-25"

# After running `npx wrangler d1 create match-schedule-db`, replace the
# database_id below with the ID Wrangler prints.
[[d1_databases]]
binding = "DB"
database_name = "match-schedule-db"
database_id = "b9318bd8-8ed2-438a-b803-7da3616b43ca"
